V18
Sleavely/docker-node-awscli pull request #4
Opened 2022-06-04 15:37 UTC by jeffxor

v18 is the next LTS version for Node. Created this PR for a new v18 build of this container.

2022-06-04 19:55 UTC, Sleavely requested changes
This is great, thank you! 🙌 

Before merging it would be great if you could address the review-comments and update the README with a reference to `v18` in the "Automatic updates" section.

2022-06-04 19:55 UTC, Sleavely commented on .github/workflows/v18.yml
> +      - 'v16'
This should probably be `v18`

2022-06-04 19:55 UTC, Sleavely commented on .github/workflows/v18.yml
> +          tags: ${{ github.workflow }},sleavely/node-awscli:latest
Since version 18 will be `latest`, could you remove that tag from `v16.yml`?

2022-06-07 15:09 UTC, jeffxor commented
@Sleavely should be good to merge. Thanks

2022-06-10 15:49 UTC, jeffxor commented
@Sleavely anything else I need to do to get this merged

2022-06-11 07:58 UTC, Sleavely approved these changes

2022-06-11 07:59 UTC, merged

2022-06-11 08:00 UTC, Sleavely commented
Looks good, thank you so much for taking the time.